### PR TITLE
Fix the integration tests.

### PR DESCRIPTION
**Pull request by HosseinYousefi**
closes dart-lang/native#625

@mahesh-hegde  It's interesting that the normal tests didn't fail with a wrong return type for `add` method.

### CODE REVIEW

**Review by dcharkes — APPROVED** [review]
gradle files 😨  ... run! 🏃‍♂️

**Comment by HosseinYousefi** [comment]
Haha, same problem as https://github.com/dart-lang/native/pull/40#issuecomment-1547775663

Just gotta yoink the `apt-get update` here as well...

**Comment by HosseinYousefi** [comment]
It already had the apt-get updates so just re-ran the tests...

**Comment by mahesh-hegde** [comment]
> @mahesh-hegde It's interesting that the normal tests didn't fail with a wrong return type for add method.

A lot more spec violations fail on Android but pass silently on standalone. Part because of CheckJNI and some could be because default implementation is a little permissive too.

**Pull request merged**
