### PR TITLE
Configure autopublishing

### LINKED ISSUE #184: Setup automated publishing
https://dart.dev/tools/pub/automated-publishing

### PR DESCRIPTION
**Pull request by HosseinYousefi**
Closes #184. Can you please check if I'm doing everything correctly @devoncarew?

### CODE REVIEW

**Comment by HosseinYousefi** [comment]
It seems that I need to use a Flutter specific releaser as the packages rely on Flutter.

**Comment by mosuem** [comment]
Done!

**Comment by dcharkes** [comment]
> * Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 3.1.0-262.3.beta, consider publishing the package as a pre-release instead.

It actually caught something! This should be `3.1.0` stable right?

**Comment by HosseinYousefi** [comment]
> > * Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 3.1.0-262.3.beta, consider publishing the package as a pre-release instead.
> 
> It actually caught something! This should be `3.1.0` stable right?

Yes, I didn't depend on 3.1.0 before since the beta CI was failing.

**Review by dcharkes — APPROVED** [review]
LGTM! Ship it! 🚚

**Pull request merged**
