### PR TITLE
bump jackson-databind to 2.14.0-rc2

### PR DESCRIPTION
**Pull request by mahesh-hegde**

### CODE REVIEW

**Comment by mahesh-hegde** [comment]
Seems like 2.14.0-rc1 adds a new provided dependency which is not downloaded properly using maven. It can be handled by specifying all transitive deps. But if dependabout alerts are gone, I'd prefer to leave it at 2.13.4 in tests.

**Comment by dcharkes** [comment]
> Seems like 2.14.0-rc1 adds a new provided dependency which is not downloaded properly using maven. It can be handled by specifying all transitive deps.

That is annoying. 😒 

> But if dependabout alerts are gone, I'd prefer to leave it at 2.13.4 in tests.

I don't know how to see if dependabot alerts are gone before merging. I don't think dependabot distinguishes between test and non-test dependencies. Maybe @jonasfj knows.

**Comment by mahesh-hegde** [comment]
For me, two alerts both point to the POM in summarizer source.

**Comment by dcharkes** [comment]
We can merge this one and find out 🙊

**Comment by mahesh-hegde** [comment]
I am 99% sure this is sufficient. Both alerts are on databind depended upon in jnigen/java/pom.xml

**Review by dcharkes — APPROVED** [review]

**Comment by mahesh-hegde** [comment]
Are dependabout alerts gone?

**Pull request merged**
